---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: servicebinding.io/postgresql
stringData:
  type: postgresql
  provider: postgresql
  host: demo-db
  port: '5432'
  database: cGV0Y2xpbmlj
  username: cGV0Y2xpbmlj
  password: cGV0Y2xpbmlj
