apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-db
spec:
  selector:
    matchLabels:
      app: petclinic-db
  template:
    metadata:
      labels:
        app: petclinic-db
    spec:
      containers:
      - name: petclinic-postgres
        image: postgres:18.3
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: demo-db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-db
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: demo-db
              key: database
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: postgresql
        livenessProbe:
          tcpSocket:
            port: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
      volumes:
        - name: postgress-data-volume
          persistentVolumeClaim:
           claimName: petclinic-db-pvc
