apiVersion: v1
kind: PersistentVolume
metadata:
  name: petclinic-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: petclinic-storage # Links this manual disk to your StorageClass
  hostPath:
    path: /data/postgres # Creates a safe directory inside Docker Desktop
