apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: api-server
          image: my-app-image:latest
          # INPUT ENVIRONMENT VARIABLES DIRECTLY FROM THE SYNC'D SECRET:
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-db-secret
                  key: db_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-db-secret
                  key: db_pass

