apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-db-pvc
spec:
  storageClassName: petclinic-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
